<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPAMYERW004D" ignored="0" name="api" tests="1" failures="1" timestamp="2022-09-29T23:53:25 AMT" time="8.213" errors="0">
  <testcase name="apiUseCase" time="7.471" classname="api.ApiTestCase">
    <failure type="java.lang.AssertionError" message="This Pilot is not among the starships&amp;apos; pilots... expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: This Pilot is not among the starships' pilots... expected [true] but found [false]
at api.ApiTestCase.apiUseCase(ApiTestCase.java:35)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 34 stack frames]]>
    </failure>
  </testcase> <!-- apiUseCase -->
</testsuite> <!-- api -->
