<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="All" duration-ms="27194" started-at="2022-09-29T23:53:17 AMT" finished-at="2022-09-29T23:53:44 AMT">
    <groups>
    </groups>
    <test name="api" duration-ms="8213" started-at="2022-09-29T23:53:17 AMT" finished-at="2022-09-29T23:53:25 AMT">
      <class name="api.ApiTestCase">
        <test-method status="PASS" signature="setBaseUri()[pri:0, instance:api.ApiTestCase@80503]" name="setBaseUri" is-config="true" duration-ms="681" started-at="2022-09-29T23:53:17 AMT" finished-at="2022-09-29T23:53:18 AMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setBaseUri -->
        <test-method status="FAIL" signature="apiUseCase()[pri:0, instance:api.ApiTestCase@80503]" name="apiUseCase" duration-ms="7471" started-at="2022-09-29T23:53:18 AMT" finished-at="2022-09-29T23:53:25 AMT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[This Pilot is not among the starships' pilots... expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: This Pilot is not among the starships' pilots... expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertTrue(Assert.java:56)
at api.ApiTestCase.apiUseCase(ApiTestCase.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1259)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:284)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:75)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:119)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- apiUseCase -->
      </class> <!-- api.ApiTestCase -->
    </test> <!-- api -->
    <test name="gui" duration-ms="18954" started-at="2022-09-29T23:53:25 AMT" finished-at="2022-09-29T23:53:44 AMT">
      <class name="gui.GuiTestCase">
        <test-method status="PASS" signature="browserSetup()[pri:0, instance:gui.GuiTestCase@60285225]" name="browserSetup" is-config="true" duration-ms="4312" started-at="2022-09-29T23:53:25 AMT" finished-at="2022-09-29T23:53:29 AMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserSetup -->
        <test-method status="PASS" signature="useCaseTest()[pri:0, instance:gui.GuiTestCase@60285225]" name="useCaseTest" duration-ms="13890" started-at="2022-09-29T23:53:29 AMT" finished-at="2022-09-29T23:53:43 AMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- useCaseTest -->
        <test-method status="PASS" signature="browserTearDown()[pri:0, instance:gui.GuiTestCase@60285225]" name="browserTearDown" is-config="true" duration-ms="749" started-at="2022-09-29T23:53:43 AMT" finished-at="2022-09-29T23:53:44 AMT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserTearDown -->
      </class> <!-- gui.GuiTestCase -->
    </test> <!-- gui -->
  </suite> <!-- All -->
</testng-results>
